# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mm-compass-templates}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tobias Adam"]
  s.date = %q{2010-07-07}
  s.email = %q{tobias.adam@mindmatters.de}
  s.files = [
    ".gitignore",
     "Rakefile",
     "VERSION",
     "lib/mm-compass-templates.rb",
     "lib/stylesheets/_mm-compass-templates.sass",
     "lib/templates/project/README.md",
     "lib/templates/project/layout/_grid.sass",
     "lib/templates/project/layout/_layout_elements.sass",
     "lib/templates/project/look/_colors.sass",
     "lib/templates/project/look/_typography.sass",
     "lib/templates/project/manifest.rb",
     "lib/templates/project/screen.sass",
     "mm-compass-templates.gemspec"
  ]
  s.homepage = %q{http://mindmatters.de}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A collection of compass templates and patterns used by mindmatters.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

